version: "3"
services:
    app_test:
        build: .
        volumes:
          - .:/app
        working_dir: /app
        environment:
          APP_URL: "http://taxes_calculator_test_nginx:80/"
          REDIS_HOST: "taxes_calculator_test_redis"
          REDIS_PORT: 6379
          REDIS_PERSISTENCE_DATABASE: 6
        container_name: taxes_calculator_test_php

    nginx:
        image: nginx:1.15.8-alpine
        ports:
          - 127.0.0.1:${NGINX_PORT}:80
        volumes:
          - .:/app
          - ./docker/nginx-test/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
        container_name: taxes_calculator_test_nginx

    redis_test:
        image: redis:7.2-alpine
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        container_name: taxes_calculator_test_redis

